version: "3.1"

services:
  web:
    build: .
    hostname: website
    restart: always
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: website
      DB_CONNECTION_LIMIT: 5
    networks:
      - nya
      - proxy

  database:
    image: mariadb
    restart: always
    hostname: database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MARIADB_DATABASE: website
    networks:
      - nya
networks:
  proxy:
    external: true
  nya:

