version: "3.1"

services:
  web:
    build: .
    hostname: website
    restart: always
    environment:
      DB_HOST: server ip
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: website
      DB_CONNECTION_LIMIT: 5
    networks:
      - nya
      - proxy
networks:
  proxy:
    external: true
  nya:
